apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: member-web
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: member-web
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 90
